### ISSUE TITLE
healthcheck_total{status=failure|success} not published until counter >= 1

### ISSUE THREAD

**Issue by sylvainle** [appclacks/cabourotte#23]
healthcheck_total{status=failure|success} is not published until counter >= 1 (an app under healthcheck can't be displayed in all charts when availability is 0% or 100%)

result :

![Capture d’écran 2023-02-07 162134](https://user-images.githubusercontent.com/9676962/217286453-7ce8d779-4f56-4770-a1ac-8c9cbd2042a1.png)

example metrics for 0% availability :

- currently : 
```
(...)
# HELP healthcheck_total Count the number of healthchecks executions.
# TYPE healthcheck_total counter
healthcheck_total{name="flux-source-controller",status="failure"} 3
(...)

```
- proposal :
```
(...)
# HELP healthcheck_total Count the number of healthchecks executions.
# TYPE healthcheck_total counter
healthcheck_total{name="flux-source-controller",status="failure"} 3
healthcheck_total{name="flux-source-controller",status="success"} 0
(...)
```

**Comment by mcorbin** [comment]
Hello,

it's the default behavior of the Golang Prometheus client so I prefer to keep it like that for now.
